name: the_good_doctor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_bloc: ^8.1.6

  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0

  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
 #NetWorking
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2
  pretty_dio_logger: ^1.4.0
  # Localazition
  intl: ^0.18.1
  easy_localization: ^3.0.7
  
  flutter_native_splash: ^2.3.5

  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.otf
        - asset: assets/fonts/Inter-Medium.otf
        - asset: assets/fonts/Inter-Regular.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
