# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lean for android firebase App Distributions"
  lane :firebase_Distributions do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart"
  firebase_app_distribution(
    app: "1:812061092925:android:206d375f9f12622db80e54",
    firebase_cli_token:ENV['FIREBASE_CLI_TOKEN'],
    android_artifact_type:"APK",
    android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
    testers:"a95526766@gmail.com",
    release_notes:"Fast line firebase distributions"
  )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
